### PR TITLE
added script to build docker image and run containers on non-windows platforms

### PR DESCRIPTION
**Pull request by itised**
I've also parameterized the image tag name, and made rebuilding the image optional.

The tag name can be set using the `-i` flag, and the `-r` flag indicates whether the image should be rebuilt:

`./build_docker.sh -r -i custom-image-tag`

The image will also always be built if it does not already exist. 

I've also made all the commands run in temporary containers.

### CODE REVIEW

**Comment by itised** [comment]
I kept the naming of the script the same as the windows version
(build_docker.sh), but maybe "build.sh" or "generate.sh" would be better, since its real purpose is to build/generate the keyboard files.

**Comment by joshreve** [comment]
This has a slightly different intent than what I ended up configuring.  This looks like it is intended to be a one time run to build a keyboard.  I think this is a good idea.  I think it needs a different name though since the other one is designed to create containers to run by selection from docker.  That ends up being a different use case.  

I could see making a .sh and .bat named generate that does just that.  As you have it setup now it will run the BIG release build process that is really a rare thing to run and mostly intended for me and for the release process.

Do you want to modify it and rename is generate or should I merge it then make the mods?  Either works for me since it is a relatively fast change.

**Comment by itised** [comment]
It was intended to be exactly that. Being able to edit the run_conig.json file and then run one command to get a keyboard was my goal.

I honestly just copied the commands from the build_docker.bat file without thinking at all about what each one did, but I could just remove running the containers for generate_configuration.py and model_builder.py scripts.

Alternatively, I could require a parameter to specify which script you would like to run, so that you would do something like:

`./generate.sh build` to run dactyl_manuform.py
`./generate.sh configure` to run generate_configuration.py
`./generate.sh release` to run model_builder.py

If you let me know which path you'd prefer, I can make the changes and push the updates.

**Comment by itised** [comment]
I renamed the script to "run.sh" and it now requires an argument to specify which script you want to run.

I also added a `help` option to make the whole process a bit friendlier

**Comment by itised** [comment]
Why does generate_configuration.py run dactyl_manuform.py, instead of just generating the run_config.json file and then finishing?

**Comment by itised** [comment]
While updating the `run` script I realized I wanted to be able to save my various builds without needing a branch for each; since run_config.json was kept in version control it proved cumbersome.

I just pushed another update to allow for multiple config files. `run` can now generate config files and build "things" using a specific config file.

I honestly am just sort of doing what works for me here, without truly understanding the original intentions of the scripts. So I can just maintain a fork of my own if this isn't a direction you want to go. But if you do see some value in it, let me know where I've gone too far astray or broken some existing process and I can make the changes.

**Comment by itised** [comment]
Also, I left model_builder.py alone. I considered having it dump all the configs it generates to the new configs directory, or possibly to a subdirectory (maybe ./configs/releases?). That way a user could generate a bunch of the most common builds and then just copy/edit them.  In which case I was going to also stop model_builder.py from running dactyl_manuform.py, and maybe create another script to either:

- build all the configs in the configs directory 
- build all the configs matching a pattern
- allow multiple configs to be passed in, and build all that are specified

I also considered allowing a directory name to be passed in and then building everything in that directory. But I didn't add the ability to use subdirectories to the other scripts, and since I'm not entirely sure how model_builder.py is really used, I decided to just not do anything.

**Comment by joshreve** [comment]
> Why does generate_configuration.py run dactyl_manuform.py, instead of just generating the run_config.json file and then finishing?

I keep meaning to undo that.  It was my lazy way of doing quick testing.  I added the good old `if __name__ == '__main__':` to build for me without running two files while debugging.  Thanks for reminding me.

**Comment by joshreve** [comment]
On the configs, I'm considering switching to a keyboard configs directory for people to push to similar to the QMK keymaps.  Model builder is really just to create the release files for prerendered keyboards.  It needs work, but was mainly to create relevant variations of the default.  I think a directory of pushed json files would likely be better with a file that prepopulates a few.

**Comment by joshreve** [comment]
I do see value it in.  I tend to run directly out of the config file so getting someone elses take on the workflow is good.  I like that approach.  I will merge, but may tweak a bit.  I think the point of multiple configs aligns with my comment on creating something similar to the QMK setup and I will look at it.  Very good suggestions and I appreciate the thought, communication, and taking the time to do the PR.

**Comment by joshreve** [comment]
I'm going to jump to getting the second trackball cluster style in, then return to this.  I'm aiming for this weekend, but it may be later.

**Comment by joshreve** [comment]
Working on the merge.  The only thing I want to put back is the update config.  The reason is to allow older configs to get the newer parameters added without having to rebuild the whole thing.  I will push it first to get the improved then look at adding that concept back.  Also, while it is confusing, I am going to temporarily keep the load of the default file so those that have already created them don't have issues.  I will just have it check if there are any passed args and if not, just use the original file name.  I expect to migrate away from that with the configs you setup, but I don't want to mess up what people may already have working.

**Comment by itised** [comment]
That all sounds great.

I like the idea of the update config, and I only deleted it because it's never run while using the non-interactive docker images. In my head I assumed it was dead code, but I keep forgetting that I just have a different work flow.

I'm wondering if instead of explicitly running update config, it would make more sense to just automatically do an update instead of overwrite if the config file with that name already exists. It would prevent accidental overwrites, and since it's only additive and doesn't remove or alter any existing part of the config, it should never cause an issue.

**Comment by joshreve** [comment]
I merged and pushed as I think it is already an improvement.  I'm going to shift to the new workflow over time so I don't want to spend much time on the autorun.  It is how it works now and I'm giving a grace period before it all goes to configs directory based.  The configs workflow is cleaner.  I know I need to create a .bat file for windows to mimic the .sh file, but I will tackle that another day.

I removed the ignore for configs and added a gallery directory.  I want people to do PRs with their configs and add a few images for people to look through.  It will be a fun way for people to share their configs.  Maybe they will, maybe they won't, but either way I can populate a few for people to see what you can create and what the configs look like to create it.

I have a big readme update to do and will roll in the communication of the new workflow into that.  The good thing is, I think the old workflow is still fully intact so it won't disrupt anyone immediately.

**Pull request merged**
