### PR TITLE
Add trackball thumb cluster

### PR DESCRIPTION
**Pull request by Cjen1**
This PR adds support for a trackball.

The main idea is that the trackball is split out from the holder (a circular hole 2mm deep and 41mm wide).

The trackball mount then screws into each other clamping the mount, which should allow for easier calibration of the trackball sensor (to ensure that pushing on the ball results in upwards cursor movement).

Additionally I'm using a octagonal bounding box for the trackball to make the webbing easier to manage.

Its still very rough and ready round the edges so I'd appreciate any comments!

I've also added some NixOS tooling (though it isn't yet a complete set of all requirements).

### CODE REVIEW

**Comment by joshreve** [comment]
Nice!  I was literally just starting to tackle this after the trackball in the inner wall design.  I hope to take a look at this in the next couple days to get it included.  I may also compare the ball socket features to take the best of both or make multiple options.

**Comment by Cjen1** [comment]
@joshreve The main things that would probably be useful to you are the stuff for the socket (circle with surrounding hex), and the holder itself. I could model the socket in CAD for a spherical base, however I'm not sure if that would be useful.

Regardless I'm going to be trying to do a full print of this in the next week or so (only done small test prints so far), so I'll post pics of it when its printed :)

**Comment by joshreve** [comment]
I haven't had a change to see what you have yet, but it sounds like there are a few differences.  I built in the socket mainly to save space, but am on the fence as I considered what you are proposing with a separate trackball module as well.  Fortunately from the code side they aren't significantly different.  I either embed the imported files or just leave a round cutout for ball socket installation.  I think this can be investigated along the way.  I did generate the base geometry in CAD in pieces to make it easy to apply post import.  It is a nice workflow to allow new local geometries to be easily built, but still embed it in the case generation.

For the bearings, they are on printed rods the way I have it now, same as Ploopy.  Metal rods should work just as well, but the plastic makes it easier to install in the sloppier tolerances of 3D prints.  Easy to trim a bit to get everything to fit.  Metal rods will certainly work as well. 

Yeah, transferring to the trackball branch would be great so I can roll it into the master after it is all in good shape and reasonably tested.  The only issue is you may see the parts that I started that are similar to your work.  If we keep them named differently it should be easy to work through the details and either keep 2 trackball cluster options or refactor to one later depending on how different the approaches are.  I could see if going either way.  

I will make another clone of the repo so I can check out your changes.

**Comment by Cjen1** [comment]
So my thinking and concern regarding trackball sensor placement is that any singular place won't work for everyone, since I find that I vary on what angle my hand is to the thumb cluster. So being able to dial that in per person, per use without needing to reprint was the main idea. That being said, it may be simpler to just integrate it straight into the case.

Additionally I hadn't realised you could use 3d printed rods for the trackball, I've always used threaded holes and screws. That would certainly decrease the overhead for the mounting points as well! Anyway I think that the first thing I may do is to try and port the separate trackball module and attachment mechanism over to give a dimension of configuration.

**Comment by joshreve** [comment]
I just looked at the design and I think it is worth keeping both.  You are targeting keys above ball, I'm going for keys left and right of the ball.  I think both have a place depending on a person's preference.  Your webs look pretty solid.  Not looking forward to that part for my thumb layout.  Perhaps we can refactor to tb_low_* and  tb_high_*?  I can manage that when you think yours is ready to merge.  Fortunately, Pycharm really has an excellent refactor->rename function that rarely has issues.  Then if you pull the update and work off the new names we will be all set moving forward.

Once I get my base cluster ready I will try a merge and then we can mess with the builtin vs modular on both designs.  One thing you could look at is the best way to mount a modular design with minimum space usage.  Maybe more a CAD exercise, but critical to the modular structure.

**Review by joshreve — APPROVED** [review]

**Comment by joshreve** [comment]
Do you have a preferred cluster name for the `thumb_style` option and function names?  I'm thinking of 'JS_THUMBBALL' for mine or something of the sort.  Not feeling very creative this week.  Anyway, let me know your preference and I will refactor both into the repo hopefully this weekend.

FYI, I appreciate the contributions.  I know what a pain it is to get the webs in place so I really appreciate people doing PRs to add more geometries, especially when they are well executed like yours.

**Comment by joshreve** [comment]
Any thoughts on naming?  Otherwise I can make it TBCJ or TB2 and just change it later.  I'm looking ready to roll both in tomorrow.

**Comment by joshreve** [comment]
I have added all the features to make it integrate with the newer structure.  Let me know what you think.  Any future mods or PRs should be easy now that it is in the construction logic.  Also, feel free to do a PR with a new name or send me the name you want on it and I can modify it.  For the moment, I just left CJ as its name.

Last question, do you want to post on Reddit for it?  You created it, so I am happy to let you do the honors.  If you don't want to or if you don't want your name listed with it, let me know.  I think it is  worth posting so people see the option.  

It looks good and quite different from what I came up with.  If you do a build and get a feel for it, I'm definitely curious.

**Pull request merged**
