### PR TITLE
add support for Docker

### PR DESCRIPTION
**Pull request by martint17r**
this PR adds support to run the python scripts in a docker container.

I did have to run through some burning hoops to get cadquery running in the conda environment.

Please let me know if you prefer another solutions.

### CODE REVIEW

**Comment by joshreve** [comment]
I realize this has been a while as I had limited time to work on this until recently, but I think this is an interesting one.  I will take a look to see if this fits with the newest updates on the geometry.

**Comment by joshreve** [comment]
I like this, but just realized my updates may have broken it due to the merging of the cadquery and solid engines into one set of files with helper functions.  I will be pushing and merging them to master soon.  If you are willing to check if any minor changes are needed, I think this is a great addition.  I run virtualbox which conflicts with running docker, so if you are willing to help I'd love to include this.

**Comment by joshreve** [comment]
Working on this as I really see the value for rapid toolchain build.  Still ironing out some issues with update form.

**Comment by joshreve** [comment]
Docker support added in latest master commit.  Due to changes to the files the original pull request could not be merged with the current master.  Equivalent functionality was created.  Thanks for the suggestion, this should help people get cadquery running more easily.

**Comment by darthcircuit** [comment]
I'm not super well versed in Docker, but would it be possible to have an image for this on docker hub? I've got an Unraid server set up in my basement that I'd like to add this to so i could offload my builds onto that.

**Comment by darthcircuit** [comment]
I think i was able to answer my own question. I cloned the repo to a share on my server, and ran a modified version of for you docker script to let it run on linux:

`
docker build -t dactyl-keyboard -f /mnt/user/share/dactyl-keyboard/docker/Dockerfile .
docker run --name DM-run -d -v "$(pwd)/src:/app/src" -v "$(pwd)/things:/app/things"  dactyl-keyboard python3 -i dactyl_manuform.py
docker run --name DM-config -d -v "$(pwd)/src:/app/src" -v "$(pwd)/things:/app/things" dactyl-keyboard python3 -i generate_configuration.py
docker run --name DM-release-build -d -v "$(pwd)/src:/app/src" -v "$(pwd)/things:/app/things" dactyl-keyboard python3 -i model_builder.py
docker run --name DM-shell -d -ti -v "$(pwd)/src:/app/src" -v "$(pwd)/things:/app/things"  dactyl-keyboard
`

Afterwards, all four containers showed up in my docker list and I am able to run them. Neat!

image

**Pull request closed without merging**
