### PR TITLE
feat/bash: Bash scripts for automating Anaconda / Docker installation and management

### PR DESCRIPTION
**Pull request by RobertMcReed**
This PR introduces two new features, as well as updating the documentation to reflect the new features.

## Feat 1: Bash script `dactyl.sh`

This bash script exposes a CLI to manage the docker image and containers. It automates the setup of the contains and allows you to easily start (run), stop, rebuild, inspect, and remove the containers. It also allows you to jump into a bash session inside the shell container. It also automates the removal of all docker artifacts with an uninstaller.

The CLI operates on positional arguments to reference either the docker `image` or the containers `shell`, `run`, `config`, and `releaseBuild`, in addition to the flag which represents the desired operation.

If you do not pass a flag, you will be taken to an interactive menu where you can choose your desired operation. If no positional argument is provided you will be taken to a main menu.

## Feat 2: Bash script `conda.sh`

This script is much simpler than the other. This just automates the installation of all dependencies if you are using Anaconda for your build environment. It allows provides an uninstaller if you invoke it with `--uninstall`.

### CODE REVIEW

**Comment by joshreve** [comment]
I really like this, but I need to make sure this is the preferred path for people before adding too many workflows due to overhead when there are changes.  

I have a poll out on Reddit on preferred way to run a generator and on what platform.  If linux / docker is dominant I will very likely incorporate this.  If windows ends up dominant, I may still merge it, I just need to make sure I don't create too many methods of operation.  I'm trying not to end up with a pile of both .bat and .sh files.  I'm hoping one comes out as the clear winner so I can focus my efforts.

**Comment by RobertMcReed** [comment]
Yup, that makes perfect sense. For what it's worth I did test this with Windows Subsystem for Linux (not the full workflow, but the menu works at least), so that's another possibility for the Windows folks.

I totally get not wanting to duplicate the work, especially as the project grows. My goal with this was to provide an avenue for the non-Windows folks and to automate as much as possible to make it easier for those who are less familiar with the tooling involved but would still benefit from the generator.

Either way, I enjoyed writing the script and learned some things in the process, so I'm good with whatever path you choose.

**Comment by freznel10** [comment]
I just used the new workflow on Windows and it worked nicely.

**Comment by RobertMcReed** [comment]
> I just used the new workflow on Windows and it worked nicely.

Nice! @freznel10 was this with WSL or some other way?

**Comment by joshreve** [comment]
Looking at the poles on reddit, linux command line seems to be the most popular so I think I will be merging this and including it.  I've been taking a little extra time to think on this and I realized I definitely need .sh automation files.  The question will be keeping the windows side simple.  I'm going to merge these on dev now and try it out.  With @freznel10 having tried it out and I'll do a confirmation, that makes me confident to add it.  It is also nice since it is an independent addition so people can still use the original workflow if they want.

**Comment by RobertMcReed** [comment]
Good stuff, happy to see it integrated. Hopefully, people will find it helpful. Cheers.

**Comment by freznel10** [comment]
Yes, with WSL2.

**Pull request merged**
